<?php

namespace Vlabs\MediaBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMimeType($mimeType)
    {
        $qb = $this->_em->createQueryBuilder();
        return $qb
            ->select('m')
            ->from($this->_entityName, 'm')
            ->where($qb->expr()->like('m.mimeType', $qb->expr()->literal($mimeType)))
            ->addOrderBy('m.filename')
            ->getQuery()
            ->getResult();
    }
}
